---
- name: odiDevEnv
  hosts: all
  become: true
  become_method: sudo

  vars:
    java_vendor: oracle
    java_development_kit: True

    installation_os_user: 'helsi'
    installation_os_user_gecos: 'Development VM Installation user'
    installation_ora_base: '/opt/oracle'
    installation_os_group: 'helsi'

  vars_files:
    - wls-vars.yml
    - secrets.yml

  pre_tasks:
  - lvg:
      vg: vg00
      pvs: /dev/sdb


  roles:
    - helsana.java
    - helsana.oracle-weblogic
    - linux.oracle-db
#    - linux.graphical
