---
- name: odiDevEnv
  hosts: all
  become: true
  become_method: sudo

  vars_files:
    # User defined variables for infrastructure
    - infra-vars.yml
    - wls-vars.yml
    - secrets.yml

  roles:
    - role: linux-jdk
    - role: linux-graphical
    - role: linux-wls

  tasks:
  - name: get keymap
    command: localectl
    register: locale
    changed_when: False
  - name: set keymap
    command: localectl set-keymap ch-de_mac
    when: "'ch-de_mac' not in locale.stdout"

  - name: add gropu helsi
    group:
      name: helsi
      state: present
  - name: add user helsi
    user:
      name: helsi
      password: "{{ oracle_os_user_pass }}"
      shell: /bin/bash
      groups: helsi, gdm

  - name: install updates
    yum: name=* state=latest


# install Fusion Middelware
- name: install fusion middleware
  hosts: all
  become: true
  become_method: sudo
  vars:
    download_folder: /vagrant_downloads

  tasks:
  - name: extract fusion middleware archive
    unarchive:
      src: "{{ download_folder}}/V886426-01.zip"
      dest: .
      remote_src: yes
      creates: fmw_12.2.1.3.0_infrastructure.jar
  - name: create  central inventory directory
    file:
      path: /soa/oracle/middleware/oracle_home_12_2_1_3
      state: directory
      owner: helsi
      group: helsi
  - name: link oracle_home
    file:
      src: /soa/oracle/middleware/Oracle_Home
      dest: /soa/oracle/middleware/oracle_home_12_2_1_3
