---
- name: odiDevEnv
  hosts: all
  become: true
  become_method: sudo

  vars:
    java_vendor: oracle
    java_development_kit: True

    # linux.oracle-db actually works only whith theses settings
    # the must correspondent to the response files
    installation_os_user: helsi
    installation_os_group: helsi
    installation_os_user_gecos: 'Development VM Installation user'
    oracle_fs_base: '/soa/oracle'

  vars_files:
    - db-vars.yml
    - odi-vars.yml
    - wls-vars.yml
    - jdev-vars.yml
    - secrets.yml

  pre_tasks:
  - lvg:
      vg: vg00
      pvs: /dev/sdb


  roles:
    - linux.graphical # long running
    - helsana.java
    - linux.oracle-db # long running
    - linux.odi # long running
    - linux.springtoolsuite
#    - helsana.oracle-weblogic
#    - helsana.oracle-weblogic
#    - linux.jdeveloper
