- name: restart cntlm service
  service:
    name: 'cntlm'
    state: restarted


- name: set http proxy for yum
  lineinfile:
    path: /etc/yum.conf
    regexp: '^proxy='
    line: 'proxy=http://localhost:3128'
