- name: get keymap
  command: localectl
  register: locale
  changed_when: False
- name: set keymap
  command: localectl set-keymap ch-de_mac
  when: "'ch-de_mac' not in locale.stdout"

- name: add gropu helsi
  group:
    name: helsi
    state: present

- name: add user helsi
  user:
    name: helsi
    password: "{{ oracle_os_user_pass }}"
    shell: /bin/bash
    groups: helsi

- name: Add Helsana repository
  yum_repository:
    name: helsana-addon-rh7
    description: Helsana Add-On Repository RHEL 7.x
    baseurl: http://admksp01.hel.kko.ch/linux/repo/helsana/el7
    gpgcheck: no

- name: Add Helsana custom repository
  yum_repository:
    name: java-1.8.0-custom
    description: Custom Helsana Repository for Oracle JDK 1.8
    baseurl: http://admksp01.hel.kko.ch/linux/repo/3rdparty/oracle-JDK/
    gpgcheck: no

- name: install helsana ansible roles roles
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    "{{ helsana_ansible_roles }}"

- name: install additional rpm packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    "{{ package_list }}"

- name: Patch ansible-oracle-weblogic role
  patch:
    src: weblogic-role.patch
    dest: /etc/ansible/roles/helsana.oracle-weblogic/tasks/main.yml
