- name: groupinstall Server with GUI
  yum:
    name: "@^Server with GUI"
  # TODO: find a more elegant way without installing all that stuff.
  # see https://www.centos.org/forums/viewtopic.php?t=47088
- name: uninstall openjdk and dependencies (libreoffice & gnome-documents)
  yum:
    name: java-1.8.0-openjdk-headless
    state: absent
- name: install missing mesa-libGL library
  yum:
    name: mesa-libGL
- name: install missing mesa-libEGL library
  yum:
    name: mesa-libEGL

- name: update packages
  yum:
    name: '*'
    state: latest
  when: packages == "latest"
  register: update
- name: check if kernel updated
  shell: |
    LAST_KERNEL=$(rpm -q --last kernel-uek | perl -pe 's/^kernel-uek-(\S+).*/$1/' | head -1 );
    CURRENT_KERNEL=$(uname -r);
    if [ $LAST_KERNEL != $CURRENT_KERNEL ]; then echo 'reboot'; else echo 'no'; fi
  ignore_errors: true
  changed_when: false
  register: reboot_hint
- name: mark to vagrant reload
  file:
    path: /vagrant/.end_play
    state: touch
  when: reboot_hint.stdout.find("reboot") != -1
- name: stop provisioning because krenel updated
  meta: end_play
  when: reboot_hint.stdout.find("reboot") != -1

- name: get default runlevel
  command: systemctl get-default
  register: runlevel
  changed_when: False
- name: Set graphical runlevel
  command: systemctl set-default graphical.target
  when: runlevel.stdout != "graphical.target"
- name: is graphical currently active
  command: systemctl is-active graphical.target
  register: graphical
  changed_when: False
  ignore_errors: yes #there is a "bug", that exit code not 0 if inactive
- name: Switch to graphical runlevel
  command: systemctl isolate graphical.target
  when: graphical.stdout != "active"

- name: upload gnome default settings
  template:
    src: 60_helsana.default.gschema.override
    dest: /usr/share/glib-2.0/schemas/60_helsana.default.gschema.override
    owner: root
    group: root
    mode: 0644
  register: gdefaults
- name: activate gnome default settings
  command: glib-compile-schemas /usr/share/glib-2.0/schemas/
  when: gdefaults.changed
- name: restart gdm
  service:
    name: gdm
    state: restarted
  when: gdefaults.changed

- name: add user {{ installation_os_user }} to gdm group
  user:
    name: '{{ installation_os_user }}'
    group: '{{ installation_os_group }}'
    groups: '{{ installation_os_group }}, gdm'
    append: yes

- name: install X Window Virtual Framebuffer, needed to create firefox profiles
  yum:
    name: xorg-x11-server-Xvfb
    state: present
- name: Install xvfb service
  copy:
    src: 'xvfb.service'
    dest: '/etc/systemd/system/xvfb.service'
    owner: root
    group: root
    mode: 0755
- name: Start xvfb service
  service:
    name: 'xvfb'
    state: started
- name: create firefox profile
  become: True
  become_user: '{{ installation_os_user }}'
  shell: 'DISPLAY=":99" firefox -CreateProfile "{{ installation_os_user }} /home/{{ installation_os_user }}/.mozilla/firefox/{{ installation_os_user }}"'
  args:
    creates: '/home/{{ installation_os_user }}/.mozilla/firefox/{{ installation_os_user }}'
