- name: get JDK tarball (as RPM file)
  get_url:
    url:     "{{ download_url }}.rpm"
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest:    "{{ download_folder }}/{{ java_archive }}.rpm"
- name: install JDK via RPM file with yum
  yum:
    name: "{{ download_folder }}/{{ java_archive }}.rpm"
