- name: correct java version selected
  alternatives:
    name: java
    link: /usr/bin/java
    path: /usr/lib/jvm/java-1.8.0-oracle/bin/java

- name: install sql developer
  yum:
    name: /media/sf_DPF_Upgrade/12.2.1/sqldeveloper-{{ sqldeveloper_version }}-1.noarch.rpm
    state: present
- name: create sqldeveloper config directories
  file:
    path: /home/{{ installation_os_user }}/.sqldeveloper/system{{ sqldeveloper_version }}/o.jdeveloper.db.connection/
    state: directory
    mode: 0755
    recurse: True
    owner: '{{ installation_os_user }}'
    group: '{{ installation_os_group }}'
- name: import sqldeveloper connections
  copy:
    src: sqldeveloper_connections.xml
    dest: /home/{{ installation_os_user }}/.sqldeveloper/system{{ sqldeveloper_version }}/o.jdeveloper.db.connection/connections.xml
    owner: '{{ installation_os_user }}'
    group: '{{ installation_os_group }}'
