- name: Create download directory
  file:
    path: '{{ oracle_download_dir }}'
    state: directory
    owner: '{{ oracle_os_user }}'
    group: '{{ installation_os_group }}'
    mode: 0755

- name: adapt sysconfig for oracle DB
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
  with_items:
    - { name: 'fs.file-max', value: '6815744'}
    - { name: 'net.core.rmem_default', value: '262144'}
    - { name: 'net.core.rmem_max', value: '4194304'}
    - { name: 'net.core.wmem_default', value: '262144'}
    - { name: 'net.core.wmem_max', value: '1048576'}

- name: adapt security limits for oracle DB
  pam_limits:
    domain: '{{item.domain}}'
    limit_type: '{{item.limit_type}}'
    limit_item: '{{item.limit_item}}'
    value: '{{item.value}}'
  with_items:
    - { domain: '*', limit_type: 'hard', limit_item: 'nofile', value: '65536'}
    - { domain: '*', limit_type: 'soft', limit_item: 'stack', value: '10240'}


## because archive does not honor existing estracted files with unzip
- stat:
    path: '{{ oracle_download_dir }}/database'
  register: extracted

- name: Extract Oracle Archive
  unarchive:
    src: '{{ oracle_src_location }}/{{ oracle_archive }}'
    dest: '{{ oracle_download_dir }}'
  when: extracted.stat.isdir is not defined or not extracted.stat.isdir

- name: Copy response files
  copy:
    src: '{{ role_path }}/files/{{ item }}'
    dest: '{{ oracle_download_dir }}/'
    owner: '{{  oracle_os_user }}'
    group: '{{  oracle_os_group }}'
    remote_src: True
    force: no
  with_items: '{{ oracle_response_files }}'
